### ISSUE TITLE
Incompatibility with fs ".native" functions

### ISSUE THREAD

**Issue by Eric162** [heimdalljs/heimdalljs#151]
https://github.com/heimdalljs/heimdalljs/blob/18917d3e9386ca07d842bc2e2be81d3573255f18/packages/%20heimdall-fs-monitor/index.js#L80

This code is too limited in scope, as there are 2 functions, [realpath.native](https://nodejs.org/api/fs.html#fs_fs_realpath_native_path_options_callback) and [realpathSync.native](https://nodejs.org/api/fs.html#fs_fs_realpathsync_native_path_options) which are not direct members of the fs exports.

Other than missing out on the data that would come with these 2 functions, there is also an issue with compatibility with `fs-extra@^10` due to this change:
https://github.com/jprichardson/node-fs-extra/pull/887

Because heimdall is replacing these functions, the `.native` function property becomes `undefined`, and causes a build-time TypeError as universalify tries to wrap `undefined` and cannot find a `name` property.

**Comment by hjdivad** [comment]
@Eric162 please confirm this resolves your issue and i'll cut a release.
