### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by Turbo87** [heimdalljs/heimdalljs#68]
From reading the README it is not clear to me where the instrumentation data is available in the end. Is it written to some file? Is it available through an API? How do you get the results in a usable way?

**Comment by rwjblue** [comment]
In general, it is not written anywhere. However, in ember-cli apps it is prettty easy to get it printed to disk (or interact with it at build time from an addon hook). See https://github.com/ember-cli/rfcs/blob/master/active/0000-addon-instrumentation-experimental-hooks.md for details.

**Comment by stefanpenner** [comment]
@Turbo87 is it fair to say this issue would be addressed if the readme showed how to access the data?

**Comment by Turbo87** [comment]
@stefanpenner yes, I think that would be a good idea

**Comment by stefanpenner** [comment]
I hope to work on some heimdall stuff this weekend. If I do, I'll also improve the readme to cover this
